#ifndef I2C_COMMON_HEADER
#define I2C_COMMON_HEADER

#define I2C_SLAVE_ADDR	0x01

typedef enum {
	PING = 0,				//CHECK/DEBUG
	GET_FIRST_PAN_STATUS,	//BATTER - PAN
	BEGIN_COOKING,			//BATTER - PAN
	MAKE_PANCAKE,			//CNTRL - BATTER
	GET_BATTER_LEVEL,		//CNTRL - BATTER
	TURN_ON_COOLING,		//CNTRL - BATTER
	TURN_OFF_COOLING		//CNTRL - BATTER
	TURN_OFF_ALARM			//CNTRL - BATTER
} I2C_commands_t;

#endif